services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: hotel-api-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

volumes:
  data: